{% set name = "instaseis" %}
{% set version = "1.5.0" %}
{% set sha256 = "c4a84953c5ddfebb8c716dc099e1456a4cb33f30a32c48d5494ab3a2d0a5fdb8" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - wheel
    - numpy
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - h5py
    - numpy
    - obspy
    - tornado
    - requests
    - geographiclib
    - jsonschema
    - numba

test:
  source_files:
    - tests
  imports:
    - instaseis
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-xdist
    - click
    - netcdf4
    - responses
  commands:
    - pytest -n 2 tests

about:
  home: http://instaseis.net
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Instant Global Broadband Seismograms Based on a Waveform Database
  description: |
    Instaseis calculates broadband seismograms from Green's function databases
    generated with AxiSEM and allows for near instantaneous (on the order of
    milliseconds) extraction of seismograms. Using the 2.5D axisymmetric
    spectral element method, the generation of these databases, based on
    reciprocity of the Green's functions, is very efficient and is approximately
    half as expensive as a single AxiSEM forward run. Thus this enables the
    computation of full databases at half the cost of the computation of
    seismograms for a single source in the previous scheme and hence allows to
    compute databases at the highest frequencies globally observed. By storing
    the basis coefficients of the numerical scheme (Lagrange polynomials),
    the Green's functions are 4th order accurate in space and the spatial
    discretization respects discontinuities in the velocity model exactly. On
    top, AxiSEM allows to include 2D structure in the source receiver plane and
    readily includes other planets such as Mars.
  doc_url: http://instaseis.net
  dev_url: https://github.com/krischer/instaseis

extra:
  recipe-maintainers:
    - krischer
    - martinvandriel
    - sstaehler
