# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CuYMiiTWATaqMFYVUYlWF94gerbRzdwYpNod9nV9ZnOOsj1bch/rnhODTfoW7mc82Nbmtt/Wv0os8rHr3XV7PLVCzn718q/VxdkXO3cn5WWbhKfNoSehWKnpgpYVrTVnTc9W8webD1FaXfpRCEUoI2zSprI8VQ7Qeo1FnvmciG24ds2IRMWus7JEjgOK73VayBiPF8AgiddntY5Kl57QeSTBtptBBUH0fk57DfvrlAmat6tWXc9up82jBrAzkFbEgQwxnI8GzO9c/DfYg+TFCMT2cyDvvf6Vfr6fu+Lm5i4uqeh997CbxrscDEX9LH8bnTWUbqIA6D5wjmVWcQJTCeEJ5c0yZSuRL4POAb4iDgNG7QwkhCK1OqL0drk9J9hjt9KJIMNfpkn5hNN2dk0+Rfgfh3RijcU6rOeSP1vKmvEn3uDloqI0XU9l6Cb9xO0CzFrqDDmjl4IjUhY9fnRhUlqoMO94dyOah752EPQQw/iBQw36eDP21bHH8atXgLI0v6/9cTQhBQ7pRwvjo0Yw6rOsLamo1TIA9Jy6C+v2g8QoJQR8tNJae3aRp7nQpCBeYwNgQHX7mYgLNsLXGCXlJKof4AsPxx2IVepmF5BtcxA6csDab4ozSb5EdyXqrHcNCydfRpIB8o4haD22yJMnOMZPh2kONLHF4xyFOWP7dlE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
