travis:
  secure:
    BINSTAR_TOKEN: wE+g5vqzpac5xch4Kggz5NtYaWZOHra5teC9KM5aTwGdXTA4iyJfc/68KMoqw/ZbqvBfRSy0MoP/b+QZXpx08qvFgfKwCmJEkQ1C4SygmNvJJILtmNPflVOX83xdTq+yS/e5BaPBnYtc9kgT/oGCAjX7lmlY+uwg6CLHPUMpODS3d9O2Lz6I9zMf6HZSTJQpKLYoK3biggRYn+CrV1Y/GLbtAzBI8qiRcNuGEZoUpm4/jWVdhWbxf9HkVokV/fUqcwaFdaXQ1BvzC9mAMjBy/sXzv/2HEzxMBoNdGpcEoZbIMk60MZrpJy99r1H3Hfq11/fTuHbdS18rOjGxLJlEYHxICV9iCKvDK/KPhVdsTdUtwrapiLd3FiphGL/PpaT8QrrYc+IIN3eVbsSVXouLdSbYE+iAWAdtfmMevlfjKUM01eRmy+hufgPfmR48Y1PXUEaksplidXMukgjkueTVvMw2/TSAPYwQyqpPfTyA9/hXgsoOHzeebY9+yuKW/NPYdXaNyA7HrMqoP3/Z59aD438EsrMkXSMYtRJ4rlPnMKtsP80WDCoPfKWvYZoODA+jzJS6Jc1xniUOobD/UWsV0JyHUjUh9IDnRUhV7EGAIWnCqHYa7HZvdg3GaPdQet6lWACE085MQutColFwt+3Z9b6xeEbA017uoyPi9nZVcI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
