travis:
  secure:
    BINSTAR_TOKEN: asKSkLKIfXK/ZxyxHcV/7Haeh4ZQu85Pjdy61VaE+fGAhRKbL+T7OQn/ZIsEFhLg1m3Nx11doG9SqCsMZwJmlhUMO3OP8WamnUbRJx44jBfbCF45+u5oQK83tnk52W65Ld1DaJTBEuKroBNxKDBkxSTgSbtW/qpMZNg0MSRU0Fn05U/tVbbZDpRjS4iYrYgWHHCiV1l2RPltpnn/FxVE17rUPNOnqcPma1i/9AFGMa6D1sQ5Mo5DlJ0C8XzXXyZoLjdzJgQ7uga8rNtUBjzCcvWHD5PO4ba69jM7F2GwMHQEQcEHimpsua/1SID+WLUt+/cfhiQ18Ni2PEw4rkTaz2Ftm2hMPI5CjOyckErD+hdfS+QdAErAOhSsc77LSraYR5vAkz7r2Q06+bhp3N1HZvbNZokfLLW6k2nK1nZGjC5gjRBq2MDRmKrTTZ2g4J+3xgsPqqmSjBWR5DCKdo4XoFnsRbQkrmIDTSqAaHC32KNM0l1yhxJKvTeMA6E2AqLD2GwoFmbhw8az54ZOQx9CsDEV6N5fmM+EcWMFBDrCOuia0x5va7xkHNZlaq+2bULKEaJ3ShgwapnwhU5rHO+iy7nnj7BPO0NIgZ7OIPD8lh9tirH3ckOQuKUQ0VjCH4n81ll16zaNsRrcHl2wStCiAz7NJhH0Gz6oc0/Yt/7pTRs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
